apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: successtech/k8-network-task
          # env:
          #   - name: AUTH_ADDRESS
          #     value: "auth-service.default" #this DNS depends on your namespace
              #value: localhost # localhost wont work,apply the auth-service.yaml and do a get service to see the correct ip address to replace localhost 

